name: goodwill
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.18
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  retrofit: ^4.0.1
  dio: ^5.0.3
  retrofit_generator: ^6.0.0+1
  get_it: ^7.2.0

  # firebase
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_core_platform_interface: 4.5.2
  firebase_storage: ^11.0.6
  flutter_screenutil: ^5.7.0
  flutter_animate: ^4.1.1+1
  flutter_platform_widgets: ^3.2.0
  email_validator: ^2.1.17
  loading_indicator: ^3.1.0
  fluttertoast: ^8.2.1
  flutter_switch: ^0.3.2
  intl: ^0.17.0
  provider: ^6.0.5
  path_provider: ^2.0.14
  file_picker: ^5.2.10
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  url_launcher: ^6.1.10
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/svgs/
    - assets/images/home_page/
    - assets/images/sign_in/
    - assets/images/message_screen/
    - assets/images/manage_post/
    - assets/images/change_language/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
